name: hello world workflow
# run-name specifies what's on the workflow run (the main job under Actions tab in main section)
# this usually has the commit description, which in most cases is most useful
#run-name: This is the run-name -> Workflow triggered by ${{ github.event }} event, for @${{ github.actor }}


# allowable formats
on: [push, pull_request, workflow_dispatch]


# on:
#   push:
#     # branches:
#     #   - main
#   pull_request:
#     branches:
#       - main
#   workflow_dispatch:

permissions: {}

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo "Hello World"
        shell: bash

  goodbye:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: goodbye world
        run: echo "Goodbye World"
        shell: bash

  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
